package com.fit.googletest.xmlparser;

import interfaces.IGeneration;

import java.io.File;
import java.util.List;

/**
 * Parse xml file generated by running the google test unit source code to get
 * the status of the test case execution
 *
 * @author ducanhnguyen
 */
public interface IXMLofGoogleTestParser extends IGeneration {

    String TEST_CASE_TAG = "testcase";
    String TEST_SUITE_ATTRIBUTE = "classname";
    String TEST_CASE_ATTRIBUTE = "name";

    /**
     * Parse the xml file
     *
     * @param xmlFilePath path of xml file
     * @return
     */
    List<IGoogleTestTestcase> parseXML(File xmlFilePath);

}