# Project: SubConditionTest
# Makefile created by Dev-C++ 5.11

CPP="C:/Dev-Cpp/MinGW64/bin/g++.exe"
CC="C:/Dev-Cpp/MinGW64/bin/gcc.exe"
WINDRES  = windres.exe
OBJ      = main.o IfCondition.o Loop.o
LINKOBJ  = main.o IfCondition.o Loop.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = SubConditionTest.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

IfCondition.o: IfCondition.cpp
	$(CPP) -c IfCondition.cpp -o IfCondition.o $(CXXFLAGS)

Loop.o: Loop.cpp
	$(CPP) -c Loop.cpp -o Loop.o $(CXXFLAGS)



















































































