# Project: RunGoogleTest
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../GoogleTest/src/gtest_main.o ../GoogleTest/src/gtest-all.o ../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.o
LINKOBJ  = ../GoogleTest/src/gtest_main.o ../GoogleTest/src/gtest-all.o ../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/DucToan/Documents/GitHub/ava-master/ava/Source code/CppProjectTesting/data-test/nartoan/GoogleTest" -I"C:/Users/DucToan/Documents/GitHub/ava-master/ava/Source code/CppProjectTesting/data-test/nartoan/GoogleTest/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/DucToan/Documents/GitHub/ava-master/ava/Source code/CppProjectTesting/data-test/nartoan/GoogleTest" -I"C:/Users/DucToan/Documents/GitHub/ava-master/ava/Source code/CppProjectTesting/data-test/nartoan/GoogleTest/include"
BIN      = RunGoogleTest.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../GoogleTest/src/gtest_main.o: ../GoogleTest/src/gtest_main.cc
	$(CPP) -c ../GoogleTest/src/gtest_main.cc -o ../GoogleTest/src/gtest_main.o $(CXXFLAGS)

../GoogleTest/src/gtest-all.o: ../GoogleTest/src/gtest-all.cc
	$(CPP) -c ../GoogleTest/src/gtest-all.cc -o ../GoogleTest/src/gtest-all.o $(CXXFLAGS)

../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.o: ../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.cpp
	$(CPP) -c ../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.cpp -o ../../../../../../../../../Desktop/unit_CppProjectTesting/TestLinhTinh_test.o $(CXXFLAGS)
