# Project: Sample_R1_Sep16
# Makefile created by Dev-C++ 5.11

CPP="E:/Dev-Cpp/MinGW64/bin/g++.exe"
CC="E:/Dev-Cpp/MinGW64/bin/gcc.exe"
WINDRES  = windres.exe
OBJ      = main.o BasicType.o PointerType.o StructType.o UnionType.o ClassType.o NamespaceTest.o OpTest.o EnumType.o ArrayType.o
LINKOBJ  = main.o BasicType.o PointerType.o StructType.o UnionType.o ClassType.o NamespaceTest.o OpTest.o EnumType.o ArrayType.o
LIBS     = -L"E:/Dev-Cpp/MinGW64/lib" -L"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sample_R1_Sep16.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

BasicType.o: BasicType.cpp
	$(CPP) -c BasicType.cpp -o BasicType.o $(CXXFLAGS)

PointerType.o: PointerType.cpp
	$(CPP) -c PointerType.cpp -o PointerType.o $(CXXFLAGS)

StructType.o: StructType.cpp
	$(CPP) -c StructType.cpp -o StructType.o $(CXXFLAGS)

UnionType.o: UnionType.cpp
	$(CPP) -c UnionType.cpp -o UnionType.o $(CXXFLAGS)

ClassType.o: ClassType.cpp
	$(CPP) -c ClassType.cpp -o ClassType.o $(CXXFLAGS)

NamespaceTest.o: NamespaceTest.cpp
	$(CPP) -c NamespaceTest.cpp -o NamespaceTest.o $(CXXFLAGS)

OpTest.o: OpTest.cpp
	$(CPP) -c OpTest.cpp -o OpTest.o $(CXXFLAGS)

EnumType.o: EnumType.cpp
	$(CPP) -c EnumType.cpp -o EnumType.o $(CXXFLAGS)

ArrayType.o: ArrayType.cpp
	$(CPP) -c ArrayType.cpp -o ArrayType.o $(CXXFLAGS)




























