# Project: Sample_for_R1_2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o FnCall.o FnCall2.o ViewSource.o GenTest.o Combine.o Preprocessor.o Casting.o StorageKeyword.o
LINKOBJ  = main.o FnCall.o FnCall2.o ViewSource.o GenTest.o Combine.o Preprocessor.o Casting.o StorageKeyword.o
LIBS     = -L"E:/Dev-Cpp/MinGW64/lib" -L"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sample_for_R1_2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

FnCall.o: FnCall.cpp
	$(CPP) -c FnCall.cpp -o FnCall.o $(CXXFLAGS)

FnCall2.o: FnCall2.cpp
	$(CPP) -c FnCall2.cpp -o FnCall2.o $(CXXFLAGS)

ViewSource.o: ViewSource.cpp
	$(CPP) -c ViewSource.cpp -o ViewSource.o $(CXXFLAGS)

GenTest.o: GenTest.cpp
	$(CPP) -c GenTest.cpp -o GenTest.o $(CXXFLAGS)

Combine.o: Combine.cpp
	$(CPP) -c Combine.cpp -o Combine.o $(CXXFLAGS)

Preprocessor.o: Preprocessor.cpp
	$(CPP) -c Preprocessor.cpp -o Preprocessor.o $(CXXFLAGS)

Casting.o: Casting.cpp
	$(CPP) -c Casting.cpp -o Casting.o $(CXXFLAGS)

StorageKeyword.o: StorageKeyword.cpp
	$(CPP) -c StorageKeyword.cpp -o StorageKeyword.o $(CXXFLAGS)
