# Project: Sample_for_R1_4
# Makefile created by Dev-C++ 5.11

CPP="E:/Dev-Cpp/MinGW64/bin/g++.exe"
CC="E:/Dev-Cpp/MinGW64/bin/gcc.exe"
WINDRES  = windres.exe
OBJ      = main.o TypeDef.o NonLinear.o Complex.o PassArgs.o Age.o cities.o asa005.o r85.o asa103.o
LINKOBJ  = main.o TypeDef.o NonLinear.o Complex.o PassArgs.o Age.o cities.o asa005.o r85.o asa103.o
LIBS     = -L"E:/Dev-Cpp/MinGW64/lib" -L"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sample_for_R1_4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

TypeDef.o: TypeDef.cpp
	$(CPP) -c TypeDef.cpp -o TypeDef.o $(CXXFLAGS)

NonLinear.o: NonLinear.cpp
	$(CPP) -c NonLinear.cpp -o NonLinear.o $(CXXFLAGS)

Complex.o: Complex.cpp
	$(CPP) -c Complex.cpp -o Complex.o $(CXXFLAGS)

PassArgs.o: PassArgs.cpp
	$(CPP) -c PassArgs.cpp -o PassArgs.o $(CXXFLAGS)

Age.o: Age.cpp
	$(CPP) -c Age.cpp -o Age.o $(CXXFLAGS)

cities.o: cities.cpp
	$(CPP) -c cities.cpp -o cities.o $(CXXFLAGS)

asa005.o: asa005.cpp
	$(CPP) -c asa005.cpp -o asa005.o $(CXXFLAGS)

r85.o: r85.cpp
	$(CPP) -c r85.cpp -o r85.o $(CXXFLAGS)

asa103.o: asa103.cpp
	$(CPP) -c asa103.cpp -o asa103.o $(CXXFLAGS)

















